package ca.corbett.imageviewer.extensions.ice.llm;

import ca.corbett.imageviewer.extensions.ice.TagList;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.logging.Logger;

/**
 * Represents a response body from the chat completions API.
 * We only care about the "choices" array, which contains the text
 * content generated by the LLM. We really don't care about anything
 * else in the response.
 * <p>
 * <b>NOTE:</b> the chat completions API is considered old.
 * It's still supported, but the recommendation is to use
 * the newer "responses" API instead. We do have an AiResponseBody
 * class for that, but it's not being used yet (and has not been tested yet).
 * </p>
 * <p><b>Example response body:</b></p>
 * <pre>
 *     {
 *       "choices":[
 *        {
 *           "finish_reason":"stop",
 *           "index":0,
 *           "message": {
 *             "role":"assistant",
 *             "content":"tag1,tag2,tag3"
 *           }
 *         }
 *         ]
 *       }
 * </pre>
 *
 * @author <a href="https://github.com/scorbo2">scorbo2</a>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
public class AiCompletionsBody {

    private static final Logger log = Logger.getLogger(AiCompletionsBody.class.getName());

    @JsonProperty("choices")
    private List<ChoiceNode> choices;

    /**
     * This should typically be "stop". We'll return it
     * for informational purposes, but we don't really care about it. We just want the text content.
     */
    public String getFinishReason() {
        if (choices == null || choices.isEmpty() || choices.get(0) == null) {
            return null;
        }
        return choices.get(0).finishReason; // just return first one we find
    }

    /**
     * We should ideally only receive one choice object, but the spec says
     * we will get an array of them, so we'll handle that case without throwing exceptions.
     * We'll just append it all together and return it.
     * In the ideal case, we return choices[0].message.content, but we want to be able to handle
     * unexpected output without throwing exceptions.
     */
    public TagList getOutput() {
        if (choices == null || choices.isEmpty()) {
            TagList badList = new TagList();
            badList.add(AiConnectionManager.NO_TAGS);
            return badList;
        }

        TagList allTags = new TagList();
        for (ChoiceNode choice : choices) {
            if (choice != null && choice.message != null && choice.message.content != null) {
                String content = choice.message.content;

                // Some models return lingering </think> tags in the output.
                // I don't know why this happens.
                // The same model might return a perfectly normal tag list 9 times in a row,
                // and then give me a </think> in the middle of the list on the 10th try.
                // We'll just trim them as we see it, and log it for debugging purposes.
                if (content.contains("think>")) {
                    log.warning("The model returned thinking data in the tag list - removed.");
                }
                content = content.replace("</think>", "").trim();
                content = content.replace("<think>", "").trim(); // just in case (never seen this)

                allTags.addAll(TagList.of(content));
            }
        }
        return allTags;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
    public static class ChoiceNode {
        @JsonProperty("finish_reason")
        private String finishReason;

        @JsonProperty("message")
        private MessageNode message;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
    public static class MessageNode {
        @JsonProperty("role")
        private String role; // always "assistant" in our case

        @JsonProperty("content")
        private String content; // the actual text generated by the LLM
    }
}
